### PR TITLE
FACILITY-35 : Compatibility with OpenMRS 2.x

### PR DESCRIPTION
**Pull request by mahmed14**
Issue Link : https://issues.openmrs.org/projects/FACILITY/issues/FACILITY-35?filter=allopenissues

Change List ::
1) Removing GenericEnumUserType.java as Hibernate 4.0 handles enum types
itself
2) updating class type of frequency and period from GenericEnumUserType
to org.hibernate.type.EnumType
3) adding Openmrs API and Web Dependencies
4) adding LegacyUI dependency
5) updating Least Openmrs version to 2.0

### CODE REVIEW

**Comment by mahmed14** [comment]
@dkayiwa  , please review this pull request .

**Comment by dkayiwa** [comment]
@mahmed14 have you tested this by running the module OpenMRS platform 2.x and confirmed that it installs and works well for all its functionality?

**Comment by mahmed14** [comment]
@dkayiwa i have installed this module on openmrs 2.0.6, and added all the forms using it. it is working fine

**Comment by dkayiwa** [comment]
@mahmed14 without any of the changes in this pull request, i was able to compile and run the module. Then installed it in platform 2.x and it did install and run successfully. So what exactly is the error that this pull request is trying to solve?

**Comment by mahmed14** [comment]
@dkayiwa ,
When deployed it on OpenMRS 2.x , i got "facilitydata: Unable to find class definition for extension: org.openmrs.admin.list",
Also when i upgraded module OpenMRS version in pom.xml , I got a genericenum class  started showing errors. Because of that i have to 
updating class type of frequency and period from GenericEnumUserType
to org.hibernate.type.EnumType , in hibernate xml config file. i also added legacyUI dependency for it to run.

**did you insert any record in the module?**

**Comment by mahmed14** [comment]
@dkayiwa , i also installed this module by uploading it and also by installing it on from OpenMRS search . can u install it from OpenMRS module search. Can you try to insert any record. i got this error when installing the module. 
**facilitydata: Unable to find class definition for extension: org.openmrs.admin.list**

**Comment by dkayiwa** [comment]
How does one insert a record? I have never used this module.

**Comment by mahmed14** [comment]
@dkayiwa  , insert first questionType  then question and then forms

**Comment by dkayiwa** [comment]
What does that mean? Take me as a basic end user.

**Comment by mahmed14** [comment]
@dkayiwa  , 

so to  create a new form. first thing to add is QuestionType . For question creation , you need question type . after creating  all necessary questiontype and question . Now you can create a custom form by using question created early. 

i hope this helps you to get little idea how this is working.

**Comment by dkayiwa** [comment]
How do i create a new form? How do i add QuestionType?

**Comment by mahmed14** [comment]
@dkayiwa  , please follow this wiki
https://wiki.openmrs.org/display/docs/Facility+Data+Module

**Comment by mahmed14** [comment]
@dkayiwa , dont read the whole document just read the Administering steps , so that you can have understanding of this module

**Comment by dkayiwa** [comment]
I thought you would just list a few explicit newbie steps here.

**Comment by mahmed14** [comment]
@dkayiwa  , i am little confused regarding what you want to understand more. If you think there is any confusion , we can have skype call.

**Comment by dkayiwa** [comment]
What i mean is something like this:
1) Click on the File menu
2) Select Save
3) Enter a name in the windows that shows up.
4) Click the close button
etc

Do you see how explicit those steps are, for a newbie?

**Comment by mahmed14** [comment]
@dkayiwa , can i record a video to show you this steps ?

**Comment by mahmed14** [comment]
https://drive.google.com/file/d/1zFoS5LfQMuoHuBZjo_oU68PTQiwyhmWT/view?usp=sharing 

this is the link to video @dkayiwa

**Comment by dkayiwa** [comment]
Can you instead, upload it on utube?

**Comment by mahmed14** [comment]
@dkayiwa for now , i dont want to. Could you please accept this pull request . as i have alot of more changes which are due. And i have alot of work pending excluding facility data module. As soon this pull request is accepted . then i would start sending new pull request. i will upload new video of this module  on youtube once all new changes are made in master branch . That would make easier for alot of people regarding this module

**Comment by dkayiwa** [comment]
ok merged.

**Pull request merged**
