### PR TITLE
2.x upgrade

### PR DESCRIPTION
**Pull request by mahmed14**
hi , 

i am creating a pull request although the 2.x branch has some changes in liquibase.xml but because i was already ahead of alot of commits then i made those changes in my liquibase.xml to avoid conflicts.

### CODE REVIEW

**Comment by mahmed14** [comment]
@mseaton ,

 I thought that 2.x would be for openMRS 2.x compatible branch. Okay i will cancel this pull request.

@dkayiwa , i would cancel this pull request and generate new one with one comment against master branch.

it this fine ??

**Comment by dkayiwa** [comment]
@mahmed14 did you spot the merge conflicts?

**Comment by mahmed14** [comment]
@dkayiwa , 

yes i did but there are not major ones. Latest code is already is already copied to liquibase.xml with my changes also .

**Comment by dkayiwa** [comment]
So does it mean we just close this without merging?

**Comment by mahmed14** [comment]
@dkayiwa , you can merge it , there is no issue in it. but i think you wanted all changes in single commit , right ?

**Comment by dkayiwa** [comment]
I cannot merge because of conflicts.

**Comment by dkayiwa** [comment]
@mahmed14 are you able to resolve the merge conflicts on this?

**Comment by mahmed14** [comment]
@dkayiwa  ,

actually there is no conflict in code , this codes works fine but the problem acquired the master branch is went one commit advance which i was commited and on these branch i have gone few extra commits , so you can merge this by overriding new files, the  module will run fine because it has all the changes which master branch has .

**Comment by dkayiwa** [comment]
The github merge button is disabled because of merge conflicts. So i cannot merge.

**Comment by mahmed14** [comment]
for me resolve conflicts button is disabled. i am also unable to resolve it

**Comment by dkayiwa** [comment]
Can you do some googling with text like "git how to resolve merge conflicts"?

**Comment by mahmed14** [comment]
getting this error ,

*This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests*
image

**Comment by mahmed14** [comment]
@dkayiwa , there is no difference in conflict files. my liquibase.xml file has some additional changes which are not in master branch. by just overriding these files would resolve the issue and the module will be working fine. as i have test many part of it.

**Comment by mahmed14** [comment]
closing this pull request. creating new one .

**Pull request closed without merging**
